name: All Checks

on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install
      
    - name: Install dependencies
      run: uv sync --all-extras --dev
      
    - name: Run all tests
      run: uv run python -m pytest ./tests/
      
    - name: Run linter
      run: uvx ruff check --extend-select I,F401
      
    - name: Check formatting
      run: uvx ruff format --check .
      
    - name: Run type checker
      run: uv run pyright .